### ISSUE TITLE
No easy way to control when responsive images plugin is activated

### ISSUE THREAD

**Issue by gkop** [filepicker/filepicker-js#14]
For example, I am using masonry.js to perform my layout. My <img> tags have width: 100% but don't fall into columns until after masonry.js is initialized. Therefore I came up with this hack to delay the responsive images until I ask for it explicitly after masonry.js is initialized: https://github.com/Binti-com/filepicker-js/commit/d2638baecc629d57ea6e4eb28f473e5f439e0fb1 . It'd be nice to have a way to configure this behavior without custom patching filepicker.js .

(love the responsive images feature btw! Great work :) )

**Comment by bonomite** [comment]
Same here, it seems that the responsive images feature fires on LOAD and on RESIZE only... my list is populated after load and need a way to manually trigger the feature to fire. I have used Unveil.js (http://luis-almeida.github.io/unveil/) and they give you two good options, $("img").trigger("unveil"); where you can target an individual image... or $(window).trigger("lookup"); which looks for all images that have not been triggered yet, and trigger them. Hope this helps. Thanks. This software is really great!

**Comment by bonomite** [comment]
Perfect! Thanks
