### ISSUE TITLE
Iframe communication still needed?

### ISSUE THREAD

**Issue by francois2metz** [filepicker/filepicker-js#24]
Hi,

I was wondering if the 2 iframes created on _every pages_ that use filepicker are still needed. Even Ie8 don't need this hack. This would remove a lot of cruft.

What do you think?

**Comment by filipegiusti** [comment]
This is causing troubles with turbolinks.

**Comment by acurry** [comment]
We're also running into troubles with `react-router` when these iframes are in the DOM as well.

**Comment by francois2metz** [comment]
I tried to remove these, but the modal try to use them. These iframes also kill performance as they read localStorage every 200ms.

**Comment by szwacz** [comment]
Hello, sorry for being silent for so long. We'll try to resolve this problem in very near future.

**Comment by szwacz** [comment]
Dear users we've decided to leave this as-it-is for now, because we're now in planning stage for version 3 of our library, which for sure won't have this problem. So unfortunately this problem won't be resolved until v3 is out.

**Comment by jkburges** [comment]
Any word on the timeframe for v3?

What is the feasibility of skipping the dialog.filepicker.io iframe and just using the js file which it includes directly?

I ask because loading iframes/js files from a different domain is causing us issues for users with restrictive security configuration (that's a bit vague yes, we don't have much more information than that at this point).

**Comment by szwacz** [comment]
With ETA for v3 we're aiming for November (so patience is required).

Using javascripts loded into iframes without iframes won't work. The iframes are there on purpose and their existance is hardcoded into the codebase.

**Comment by adamjpeterson** [comment]
Any updates on v3 launch?

**Comment by tojofo** [comment]
*bump*

**Comment by szwacz** [comment]
The v3 launch estimate has been moved to end of January.
Sorry for the delay, we're doing what we can (Let the one who always deliver IT projects on time cast the first stone).

As a teaser I will say that v3 is not just an iteration on v2, but APIs and UI experience built completely from scratch. Much faster/leaner and with greater capabilities.

**Comment by adamjpeterson** [comment]
Funny as the timing is - today is the end of January. How is v3 coming along?

**Comment by gnaeus** [comment]
Any news on v3? 🙂

**Comment by bkwi** [comment]
> Any news on v3? 🙂

https://github.com/filestack/filestack-js
