### ISSUE TITLE
Bower package missing main-property

### ISSUE THREAD

**Issue by Slettan** [filepicker/filepicker-js#3]
The bower package for Filepicker is missing the "main"-property in its bower.json-file, meaning tools like wiredep won't be able to inject the script.

**Comment by krystiangw** [comment]
There is separated [bower friendly repositorium](https://github.com/krystiangw/filepicker-js-bower).
And you can find main property there https://github.com/krystiangw/filepicker-js-bower/blob/master/bower.json#L6

**Comment by Slettan** [comment]
Thanks for the reply.

That's the one I downloaded, by using `bower install filepicker-js --save`. However, the downloaded bower.json file only contains the following properties:

```javascript
{
  "name": "filepicker-js",
  "homepage": "https://github.com/krystiangw/filepicker-js-bower",
  "version": "2.0.0",
  "_release": "2.0.0",
  "_resolution": {
    "type": "version",
    "tag": "2.0.0",
    "commit": "2480d8fab7f4f7024d15146b61cb7ed300e8d0d4"
  },
  "_source": "git://github.com/krystiangw/filepicker-js-bower.git",
  "_target": "~2.0.0",
  "_originalSource": "filepicker-js"
}

**Comment by krystiangw** [comment]
You were right - 'main' property was missing . I updated it. Please update filepciekr-js version - should works fine now.
