### ISSUE TITLE
Duplicate upload button

### ISSUE THREAD

**Issue by matiastucci** [filepicker/filepicker-js#45]
I have this `input`:

```
input(
  data-fp-button-class="file-picker-button"
  data-fp-button-text="<i class='fa fa-fw fa-upload'></i>&nbsp;Upload Files"
  data-fp-multiple="true"
  style="visibility:hidden;"
)
```

and I'm creating programmatically my widget doing: `window.filepicker.constructWidget(el)` the problem is that I'm seeing 2 buttons. Seems that the library is building the button too, so when I first load the page and I'm calling `window.filepicker.constructWidget(el)` I'm seeing 2 of them. In other words, when the library is injected is building my button without me calling the `.constructWidget` method.

EDIT: here is a [JS Bin](http://jsbin.com/horavecame/edit?html,js,output)

How should I do this?

Thanks!

**Comment by szwacz** [comment]
Filestack library searches for inputs automatically on load event. If your input element is present in HTML from the start then there is no need to call `filepicker.constructWidget(el)`, this method is intended for use cases when you're loadig extra HTML after initial load event.

Does that explanation solve your problem?

**Comment by matiastucci** [comment]
Yeah, I noticed that. I'm loading Filestack, is doing it automatically just like you said but then when I come back the section I have the widget, is not appearing at all. That's because I need to construct it myself but this has the problem of the 2 buttons. Would be nice if the library had a flag or something to avoid this automatically construction.

**Comment by szwacz** [comment]
Indeed you're right. Will see what we can do.
