### ISSUE TITLE
Drag and drop causes JS error with tif/tiff files

### ISSUE THREAD

**Issue by slwen** [filepicker/filepicker-js#54]
Hi there,

Apologies if this is the wrong place but I couldn't find anywhere else to log a bug.

We've run in to an interesting bug where attempting to upload a `.tif` file via drag and drop in Safari causes filepicker to spit a JS error and fail, causing a poor user experience.

![tif-error](https://cloud.githubusercontent.com/assets/859298/22047451/f1a9958c-dd72-11e6-9c61-1913ffdcf5b0.gif)

### To reproduce:

1. Load the code at this gist: https://gist.github.com/slwen/48376c3985cd6d40666d272f7c555d7f in Safari web browser
2. Click the "pick" button
3. Attempt to drag and drop a tiff/tif file to upload

### The desired outcome:

Since the `.tif` file is a restricted format (using the `extensions` option) an error message should be displayed informing the user to pick another file type. The correct behaviour occurs when you click the _choose file_ button rather than drag and drop.

### The current behaviour:

Filepicker displays a loading state perpetually. Under the hood we see a JS error caused by Filepicker.

### For context:

Safari Version 10.0.2 (11602.3.12.0.1)
OS X 10.11.6 (15G1212) (El Capitan)

**Comment by cogKnitter** [comment]
This issue has been resolved in https://github.com/filestack/filestack-js
